# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_resource_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation_time', models.IntegerField()),
                ('area', models.IntegerField(choices=[(0, 'Cocina'), (1, 'Bar')], default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Costo del platillo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad en gramos')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Resource')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='item',
            field=models.ManyToManyField(through='menu.ResourceRecipe', to='products.Resource'),
        ),
    ]
