# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcerecipe',
            old_name='item',
            new_name='ingredient',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.IntegerField(verbose_name='Tiempo de preparacion en minutos'),
        ),
    ]
