# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20161114_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='Mojito', max_length=140),
        ),
    ]
