# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_auto_20161115_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Costo de la Orden'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Finished'), (2, 'Pending')], default=2),
        ),
    ]
