# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='price',
        ),
    ]
